version: '3'
services:
  app:
    image: squads_challenge
    build: '.'
    environment:
      PORT: 8080
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    working_dir: /app/squads_challenge/
    volumes: 
      - /app/squads_challenge/node_modules
      - ./src:/app/squads_challenge/src

  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db