version: '2.1'
services:
  db:
    container_name: DB-SERVER
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

  app:
    container_name: BACKEND-SERVER
    image: squads-challenge
    build: '.'
    environment:
      PORT: 8080
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    working_dir: /app/squads-challenge/
    volumes: 
      - /app/squads-challenge/node_modules
      - ./src:/app/squads-challenge/src
      - ./__tests__:/app/squads-challenge/__tests__
